import Link from "next/link";
import { getPageSeo, siteUrl } from "../seo";

const seo = getPageSeo("/terms");

export const metadata = {
  title: seo.title,
  description: seo.description,
  alternates: {
    canonical: `${siteUrl}${seo.path}`,
  },
};

export default function TermsPage() {
  return (
    <main className="min-h-screen px-4 py-8 text-stone-100 sm:px-6 lg:px-8">
      <section className="mx-auto max-w-4xl rounded-[32px] border border-white/10 bg-stone-950/80 p-8">
        <Link
          href="/"
          className="text-sm text-emerald-300 transition hover:text-emerald-200"
        >
          Back to ContextClean
        </Link>

        <p className="mt-8 text-xs font-semibold uppercase tracking-[0.24em] text-emerald-300/80">
          Terms of Use
        </p>
        <h1 className="mt-4 text-4xl font-semibold tracking-tight text-white">
          Terms for using ContextClean
        </h1>

        <p className="mt-6 text-sm leading-7 text-stone-300">
          Last updated: June 8, 2026.
        </p>

        <div className="mt-6 space-y-5 text-sm leading-7 text-stone-300">
          <p>
            By accessing or using ContextClean, you agree to these terms. If you do
            not agree, do not use the site.
          </p>
          <p>
            ContextClean provides browser-based utilities and supporting content for
            cleaning logs, stack traces, tracebacks, build failures, and debugging
            text before that information is reviewed by humans or shared with AI
            coding assistants.
          </p>
        </div>

        <h2 className="mt-10 text-2xl font-semibold text-white">
          Nature of the service
        </h2>
        <div className="mt-4 space-y-4 text-sm leading-7 text-stone-300">
          <p>
            The service is informational and utility-focused. It is intended to help
            users reduce noisy debugging context, not to provide professional advice,
            legal review, security guarantees, or a complete debugging diagnosis.
          </p>
          <p>
            Supporting guide pages, examples, and page text are provided for general
            educational and product-explanation purposes.
          </p>
        </div>

        <h2 className="mt-10 text-2xl font-semibold text-white">
          User responsibilities
        </h2>
        <div className="mt-4 space-y-4 text-sm leading-7 text-stone-300">
          <p>
            You are responsible for reviewing both the original input and any cleaned
            output before acting on it or sharing it. You are also responsible for
            ensuring that you have the right to process and share any text you paste
            into the tool.
          </p>
          <p>
            Do not paste passwords, API keys, access tokens, private customer data,
            confidential source code, or other restricted information into any online
            tool unless you are certain that doing so is appropriate and permitted.
          </p>
        </div>

        <h2 className="mt-10 text-2xl font-semibold text-white">
          No warranty
        </h2>
        <div className="mt-4 space-y-4 text-sm leading-7 text-stone-300">
          <p>
            ContextClean is provided on an as-is and as-available basis. No warranty
            is made that the service will always be available, error-free, complete,
            accurate, secure, or fit for a specific purpose.
          </p>
          <p>
            Cleaned output may omit details that are important in a given debugging
            situation, and any suggestions generated by third-party AI tools remain
            the responsibility of the user to verify.
          </p>
        </div>

        <h2 className="mt-10 text-2xl font-semibold text-white">
          Public community content
        </h2>
        <div className="mt-4 space-y-4 text-sm leading-7 text-stone-300">
          <p>
            Community discussions are published through the public ContextClean
            GitHub repository. You are responsible for the content you submit and
            must not post secrets, personal data, confidential code, abusive
            material, spam, or content that violates another party&apos;s rights.
          </p>
          <p>
            ContextClean may close, edit labels on, or remove links to discussions
            that are unsafe, off-topic, misleading, or abusive.
          </p>
        </div>

        <h2 className="mt-10 text-2xl font-semibold text-white">
          Third-party services
        </h2>
        <div className="mt-4 space-y-4 text-sm leading-7 text-stone-300">
          <p>
            The site may rely on third-party providers for hosting, analytics,
            advertising, or related infrastructure. Those providers may have their own
            terms and privacy policies governing the parts of the service they supply.
          </p>
        </div>

        <h2 className="mt-10 text-2xl font-semibold text-white">
          Changes to the site or terms
        </h2>
        <div className="mt-4 space-y-4 text-sm leading-7 text-stone-300">
          <p>
            ContextClean may add, remove, or change features, content, and policies
            over time. Continued use of the site after updated terms are published
            constitutes acceptance of those updates.
          </p>
        </div>

        <h2 className="mt-10 text-2xl font-semibold text-white">
          Contact
        </h2>
        <div className="mt-4 space-y-4 text-sm leading-7 text-stone-300">
          <p>
            Questions about these terms can be opened through the public
            <a
              href="https://github.com/hyuchao25/contextclean/issues/new"
              className="ml-1 text-emerald-300 hover:text-emerald-200"
            >
              ContextClean issue tracker
            </a>.
          </p>
        </div>
      </section>
    </main>
  );
}
